title: Covid-19 research
author: UBI Center
logo: _static/ubi_center_logo_wide_blue.png

html:
  use_edit_page_button      : true
  use_repository_button     : true
  use_issues_button         : true
  google_analytics_id       : "UA-138885251-1"
  baseurl                   : "https://covid.ubicenter.org"

repository:
  url: https://github.com/UBICenter/covid
  path_to_book: jb
