name: covid
channels:
- pslmodels
dependencies:
- python
- taxcalc
- plotly
- pandas
- pandas_datareader
- numpy
- pip
- pip:
  - jupyter-book
  - "git+https://github.com/MaxGhenis/microdf.git"
  - cpi
